# Generated by Django 2.2 on 2022-10-05 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('school', models.CharField(max_length=100, verbose_name='school')),
                ('snumber', models.CharField(max_length=100, verbose_name='snumber')),
                ('grade', models.CharField(max_length=100, verbose_name='grade')),
                ('classes', models.CharField(max_length=100, verbose_name='classes')),
                ('sex', models.CharField(max_length=100, verbose_name='sex')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
            ],
        ),
        migrations.CreateModel(
            name='Usertoken',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('token', models.CharField(max_length=1000)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.User')),
            ],
        ),
    ]
