# Generated by Django 4.1.3 on 2023-05-13 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_userlog"),
    ]

    operations = [
        migrations.CreateModel(
            name="Userstatus",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("user_id", models.IntegerField()),
                ("status", models.IntegerField()),
            ],
        ),
    ]
